sources:
  include:
    - TestSourcery
    - AutomaticSettingsProtocols.swift
templates:
  - Stencil/AutomaticSettings.stencil
output:
  TestSourcery/CodeGen/
args:
  settingsView: SettingsView
  settingsStructure: Settings
  settingsExternalData: SettingsExternal
  # settingsImports:
  #   - UIKit